[package]
name = "veilus-fingerprint-data"
description = "Embedded Bayesian network data for the veilus-fingerprint browser fingerprint generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
veilus-fingerprint-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zip = "2"

[build-dependencies]
zip = "2"
