[package]
name = "fingerprint-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fingerprint-core = { workspace = true }
fingerprint-data = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = "0.8"
rand_chacha = "0.3"
tracing = "0.1"
